spring:
  data:
    mongodb:
      uri: mongodb+srv://${username}:${password}@${dataname}.dtgydnp.mongodb.net/?retryWrites=true&w=majority&appName=${dataname}
      database: cms
      auto-index-creation: true

  application:
    name: hook4startup

logging:
  level:
    root: INFO



    #mongodb+srv://namdevaniket446:TOd09Wqu32PHamYn@cms.dtgydnp.mongodb.net/?retryWrites=true&w=majority&appName=cms