server:
    port: ${portnumber}
spring:
   data:
    mongodb:
      uri: mongodb+srv://${username}:${password}@${dataname}.dtgydnp.mongodb.net/?retryWrites=true&w=majority&appName=${dataname}
      database: ${dataname}

      auto-index-creation: true

application:
     name: ${nameofStartup}

     logging:
       level:
         root: INFO



